server:
  port: 8080

spring:
  application:
    name: book
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: 123456
    url: jdbc:mysql://localhost:3306/${spring.application.name}?useUnicode=yes&characterEncoding=UTF-8
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  output:
    ansi:
      enabled: always

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.book.entity
  type-handlers-package: com.book.entity.handler
  type-aliases-super-type: com.book.common.BaseEntity

logging:
  level:
    com.book.dao: DEBUG
